/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/Base/Button/Button.vue')['default']
    BaseCard: typeof import('./src/components/Base/Card.vue')['default']
    BaseCollapse: typeof import('./src/components/Base/Collapse.vue')['default']
    BaseFormInput: typeof import('./src/components/Base/Form/Input.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    NavbarBrand: typeof import('./src/components/Navbar/Brand.vue')['default']
    NavbarDarkToggler: typeof import('./src/components/Navbar/DarkToggler.vue')['default']
    NavbarItem: typeof import('./src/components/Navbar/NavbarItem.vue')['default']
    PairInput: typeof import('./src/components/Pair/Input.vue')['default']
    PairInputGroup: typeof import('./src/components/Pair/InputGroup.vue')['default']
    PairTreeItem: typeof import('./src/components/Pair/TreeItem.vue')['default']
    PairTreeView: typeof import('./src/components/Pair/TreeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeItem: typeof import('./src/components/TreeItem.vue')['default']
  }
}
