/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBackdrop: typeof import('./src/components/Base/Backdrop.vue')['default']
    BaseButton: typeof import('./src/components/Base/Button/Button.vue')['default']
    BaseButtonOutline: typeof import('./src/components/Base/Button/ButtonOutline.vue')['default']
    BaseCard: typeof import('./src/components/Base/Card/Card.vue')['default']
    BaseCardBody: typeof import('./src/components/Base/Card/CardBody.vue')['default']
    BaseCardContent: typeof import('./src/components/Base/CardContent.vue')['default']
    BaseCountryFlag: typeof import('./src/components/Base/CountryFlag.vue')['default']
    BaseLoader: typeof import('./src/components/Base/Loader.vue')['default']
    BaseModal: typeof import('./src/components/Base/Modal/Modal.vue')['default']
    BaseModalBackdrop: typeof import('./src/components/Base/Modal/ModalBackdrop.vue')['default']
    BaseModalModal: typeof import('./src/components/Base/Modal/Modal.vue')['default']
    BasePagination: typeof import('./src/components/Base/Pagination/Pagination.vue')['default']
    BasePaginationButton: typeof import('./src/components/Base/Pagination/PaginationButton.vue')['default']
    BaseRadio: typeof import('./src/components/Base/Radio.vue')['default']
    BaseTransitionFade: typeof import('./src/components/Base/Transition/Fade.vue')['default']
    DisplayModeSelect: typeof import('./src/components/DisplayModeSelect.vue')['default']
    FavoriteBtn: typeof import('./src/components/FavoriteBtn.vue')['default']
    FormModeSelect: typeof import('./src/components/Form/ModeSelect.vue')['default']
    FormPerPageSelect: typeof import('./src/components/Form/PerPageSelect.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LayoutDataView: typeof import('./src/components/Layout/DataView.vue')['default']
    LayoutModeSelect: typeof import('./src/components/Layout/ModeSelect.vue')['default']
    LayoutUser: typeof import('./src/components/Layout/User.vue')['default']
    LayoutUserDataView: typeof import('./src/components/Layout/UserDataView.vue')['default']
    ModeSelect: typeof import('./src/components/ModeSelect.vue')['default']
    Navbar: typeof import('./src/components/Navbar/Navbar.vue')['default']
    NavbarItem: typeof import('./src/components/Navbar/NavbarItem.vue')['default']
    PerPageSelect: typeof import('./src/components/PerPageSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAvatar: typeof import('./src/components/User/Avatar.vue')['default']
    UserButtonFavor: typeof import('./src/components/User/ButtonFavor.vue')['default']
    UserButtonProfile: typeof import('./src/components/User/ButtonProfile.vue')['default']
    UserCard: typeof import('./src/components/User/Card.vue')['default']
    UserCardGroup: typeof import('./src/components/User/CardGroup.vue')['default']
    UserDataView: typeof import('./src/components/User/DataView.vue')['default']
    UserFavorButton: typeof import('./src/components/User/FavorButton.vue')['default']
    UserList: typeof import('./src/components/User/List.vue')['default']
    UserListItem: typeof import('./src/components/User/ListItem.vue')['default']
    UserModal: typeof import('./src/components/User/Modal.vue')['default']
    UserProfileButton: typeof import('./src/components/User/ProfileButton.vue')['default']
    UserProfileModal: typeof import('./src/components/User/ProfileModal.vue')['default']
    UserTransitionGroup: typeof import('./src/components/User/TransitionGroup.vue')['default']
  }
}
